### ISSUE TITLE
Typo in Reponame

### ISSUE THREAD

**Issue by epoyraz** [Microsoft/Rosyln-Analyzer-ToStringWithoutOverride#1]
You have a typo in the name of your repo.
It's Roslyn not **Rosyln**

**Comment by danstiner** [comment]
Thanks for pointing this out! I don't have control of this repository, but I've updated the name of my fork where future NuGet package versions will point to: https://github.com/danstiner/Roslyn-Analyzer-ToStringWithoutOverride
